services:
  couchdb:
    image: couchdb:3.4.1
    container_name: sumptureg-couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    networks:
      - sumptureg

  server:
    image: nginx:alpine
    container_name: sumptureg-server
    depends_on:
      - couchdb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./result/var/html:/usr/share/nginx/html:ro
    networks:
      - sumptureg

networks:
  sumptureg:
    driver: bridge
